### ISSUE TITLE
[Bug] Memory Leak on inferance

### ISSUE THREAD

**Issue by cxf2015** [openvinotoolkit/openvino#11669]
##### System information (version)
- OpenVINO = 2022.1.0.643
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification: Model Conversion
- Framework: pytorch(if applicable)
- Model name: OCR (if applicable)

##### Detailed description
when i use OpenVINO2022.1.0.643 to inferance a text image "infer_request.infer();" always Memory leaks.
code list:
############################################################################

######################################################################

##### Steps to reproduce

    ```.cpp
    // C++ code example
    ```
    reco_network400 = core400.read_model(string(modelPath), modelPathBin);
    auto d400 = reco_network400->input(0).get_partial_shape();
    d400[3] = -1;
    reco_network400->reshape(d400);
    const ov::Layout tensor_layout400{ "NHWC" };
    ov::preprocess::PrePostProcessor ppp400(reco_network400);
    ov::preprocess::InputInfo& input_info400 = ppp400.input();
    input_info400.tensor().set_element_type(ov::element::f32).set_layout(tensor_layout400);
    input_info400.model().set_layout("NCHW");
    ppp400.output().tensor().set_element_type(ov::element::f32);
    reco_network400 = ppp400.build();
    compiled_model400 = core400.compile_model(reco_network400, "CPU");
    infer_request400 = compiled_model400.create_infer_request();
    ......
        image.convertTo(image, CV_32FC1, 1.0f / 255.0f);
        image = (image - 0.588) / 0.193;
        vector<vector<float>> output;
        size_t size = long(width) * long(height) * long(image.channels());
        std::shared_ptr<float> _data;
        _data.reset(new  float[size], std::default_delete<float[]>());
        cv::Mat resized(cv::Size(width, height), image.type(), _data.get());
        cv::resize(image, resized, cv::Size(width, height));
        ov::element::Type input_type = ov::element::f32;
        ov::Shape input_shape = { 1, (long unsigned int)height, (long unsigned int)width, 1 };
        //ov::Shape input_shape = { 1, 1,(long unsigned int)height, (long unsigned int)width };
        ov::Tensor input_tensor = ov::Tensor(input_type, input_shape, _data.get());
        infer_request400.set_input_tensor(input_tensor);
        infer_request400.infer();
        ov::Tensor& output_tensor = infer_request400.get_output_tensor();

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [ ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by Iffa-Meah** [comment]
@cxf2015 could you share your model? and what model and topology it is?

**Comment by cxf2015** [comment]
hi @Iffa-Meah Relevant information has been sent to your email. thank you!

**Comment by Iffa-Meah** [comment]
@cxf2015,

I tested your IR model with [OpenVINO Benchmark Python Tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html) and it seems that there are issues related to shapes.

Could you share your conversion command?
It is best to validate the memory leak issue using OpenVINO Official Samples since they had been properly designed to work with supported devices.

**Comment by cxf2015** [comment]
@Iffa-Meah are you mean conversion command"python mo.py --input_shape=[1,1,32,?] --input_model=D:\textreg.onnx --output_dir=D:\"
The error in the screenshort should be an input image size problem.
Is it my conversion the model to the OpenVINO IR format problem?

**Comment by Iffa-Meah** [comment]
@cxf2015 does the same issue occur if you set the input shape to static?
python mo.py --input_shape=[1,1,32,280] --input_model=D:\textreg.onnx --output_dir=D:

If possible could you share your native model?

**Comment by cxf2015** [comment]
@Iffa-Meah The error does not occur if set the input shape to static, in addition "--input_shape=[1,1,32,280]" or "--input_shape=[1,1,32,?]" also get same result.

**Comment by cxf2015** [comment]
@Iffa-Meah onnx file has been sent to your email, do you need another files?

**Comment by Iffa-Meah** [comment]
@cxf2015,

Starting from the 2020.4 release, OpenVINO™ supports reading native ONNX models. 
So you should be able to infer the ONNX model without converting if nothing's wrong with it/supported.

However, the inference failed for your native ONNX model. This relates to importing the input stream with binary protobuf.
<img width="565" alt="BenchmarkONNX" src="https://user-images.githubusercontent.com/79643476/168931520-b95af497-9714-4614-86e8-5d133b07740c.png">

Did you manage to run this model with any of the [Official OpenVINO Sample Apps](https://docs.openvino.ai/latest/openvino_docs_OV_UG_Samples_Overview.html) before?

One of the OpenVINO supported ONNX models is this [Mask R-CNN model](https://docs.openvino.ai/latest/openvino_docs_MO_DG_prepare_model_convert_model_onnx_specific_Convert_Mask_RCNNhtml) which a good option for a quick test.

**Comment by cxf2015** [comment]
@Iffa-Meah i test reading native ONNX model to inference, have same problem. Memory usage is growing all the time. if i fix image input size there is no memory leak. 
i convert onnx file by " 
data = torch.randn(1,1,32,280)
torch.onnx.export(model, data, 'textrec.onnx', export_params=True, opset_version=12)"  are there any mistakes?
otherwise i will test official model to see if anyone have same problem. thanks.

**Comment by cxf2015** [comment]
@Iffa-Meah I think is may be caused by nn.lstm module. There are no memory leaks if LSTM is not used in the model. Is this normal?

**Comment by cxf2015** [comment]
@Iffa-Meah when i use  nn.LSTMCell replace nn.LSTM no memory leaks.
code:
        self.rnn_forward = nn.LSTMCell(nIn, nHidden ) 
        self.rnn_backward = nn.LSTMCell(nIn, nHidden ) 
        # nn.LSTM(nIn, nHidden, bidirectional=True)
Is this normal?

**Comment by Iffa-Meah** [comment]
@cxf2015 the main thing here is to make sure that the model itself is supported by OpenVINO which means it should be able to run with any suitable OpenVINO Official Samples. This is why I asked the above questions (whether you had validated this model to be compatible with OpenVINO) since from my side, I can see that the model is not able to be inferred from the OpenVINO perspective which is likely to be incompatible.

If the model itself is incompatible/not supported by OpenVINO, no matter what networks/layers are used, issues are expected.
OpenVINO supports varieties of frameworks & topologies such as Tensorflow, ONNX, Caffe but they are limited.

Your custom code definitely would run because I don't see any error handler to check whether the model failed to be loaded with the OpenVINO API. The quickest is to use the OpenVINO Benchmark Python Tool.

**Comment by cxf2015** [comment]
@Iffa-Meah i tested this model by Benchmark Python Tool, if i use nn.LSTMCell to implement a Bidirectional-RNN OpenVINO works well, but if i use nn.LSTM memory leaks occurs. 
meybe OpenVINO handled differently on nn.LSTM( ) nn.LSTMCell(), and need to optimize nn.LSTM( ).

**Comment by Iffa-Meah** [comment]
we'll further investigate this and get back to you soon

**Comment by jgespino** [comment]
@cxf2015 Could you share how you are detecting the memory leak using benchmark_app on windows? and how much memory leak are you seeing? Also, what CPU SKU are you using?

I used your model with benchmark_app and valgrind on my linux system and I saw the following. 

![image](https://user-images.githubusercontent.com/18014973/170592539-730a051b-d871-4280-94ea-677f44a63175.png)

**Comment by cxf2015** [comment]
@jgespino hi, i use CPU(11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz) on windows10, run test.py to OCR a picture, and each text line image has a 2-3M memory boost, adding up all the time.

**Comment by jgespino** [comment]
@cxf2015 I did notice that too when running your test.py but the memory goes back to down after the script ends. On your system does it continue to build up even after the script ends?

Running your script on Linux with valgrind, shows a memory leak but running your model (same as test.py) with benchmark_app does not show a memory leak.

```
valgrind --tool=memcheck --leak-check=yes python3 test.py
 LEAK SUMMARY:
==516826==    definitely lost: 32 bytes in 1 blocks
==516826==    indirectly lost: 33 bytes in 2 blocks
==516826==      possibly lost: 431,528 bytes in 414 blocks
==516826==    still reachable: 6,543,857,203 bytes in 1,758,616 blocks
==516826==                       of which reachable via heuristic:
==516826==                         stdstring          : 6,119,791 bytes in 112,282 blocks
==516826==                         newarray           : 1,584 bytes in 6 blocks
==516826==         suppressed: 20,537 bytes in 8 blocks
==516826== Reachable blocks (those to which a pointer was found) are not shown.
==516826== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

```
valgrind --tool=memcheck --leak-check=yes benchmark_app -m torch-jit-export-tmp.xml
==524851== LEAK SUMMARY:
==524851==    definitely lost: 0 bytes in 0 blocks
==524851==    indirectly lost: 0 bytes in 0 blocks
==524851==      possibly lost: 188,884 bytes in 110 blocks
==524851==    still reachable: 2,022,171 bytes in 2,273 blocks
==524851==                       of which reachable via heuristic:
==524851==                         stdstring          : 5,725 bytes in 144 blocks
==524851==         suppressed: 32 bytes in 1 blocks
==524851== Reachable blocks (those to which a pointer was found) are not shown.
==524851== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Comment by cxf2015** [comment]
@jgespino thanks. that means IR model (ONNX model) no memory leak, but use openvino core show a memory leak? is that so?
After several times of testing, we found that the RNN can only be used at a fixed size without causing memory leaks.

**Comment by jgespino** [comment]
@cxf2015 Yes, maybe it's something specific to your code as I am not seeing it when using your model and the benchmark_app. Do you see a memory leak when using your RNN with benchmark_app and dynamic input?

**Comment by cxf2015** [comment]
@jgespino how to input different size images with benchmark_app?

**Comment by riverlijunjie** [comment]
You can use "--data_shape" to make generate difference shape tensor, for example:

./benchmark_app -m ~/workspaces/inference.pdmodel -shape=[-1,3,960,960] -data_shape=[2,3,960,960][5,3,960,960] -niter=100

**Comment by jgespino** [comment]
@cxf2015 This looks like a different model from your original issue (textreg.xml) which has only 1 input. Could you share the new model (my email is on my profile), input image 0.jpg and a screenshot of what you are seeing?

**Comment by cxf2015** [comment]
@jgespino Relevant files have been sent to your email.thanks

**Comment by cxf2015** [comment]
@jgespino thanks. But if inferencing keep running, memory will keep growing until out of memory. Is that normal?  Ideally, large image will take up more memory, small image will take up less memory. it seems to be no memory free on some processing modules.

**Comment by jgespino** [comment]
@cxf2015 It's expected with Dynamic shapes as mentioned in this [guide](https://docs.openvino.ai/latest/openvino_docs_OV_UG_DynamicShapes.html).

>  Also using the dynamic shapes can bring more overheads in memory and running time per each inference call depending on hardware plugin and model used.

**Comment by riverlijunjie** [comment]
There is PR can stop memory continuous increasing in dynamic shape inference scenario, which fixed the rnn cache miss issue so as to avoid creating lots of duplicated primitives, this PR has been merged into master branch, you can have a try.
PR: https://github.com/openvinotoolkit/openvino/pull/12053

**Comment by cxf2015** [comment]
@riverlijunjie old version memory usage:
![image](https://user-images.githubusercontent.com/11493837/177741756-7a6cdbf8-1e84-41de-af4b-e48745709624.png)
new code looks like can stop memory continuous increasing, but that is a lot of memory usage:
![image](https://user-images.githubusercontent.com/11493837/177742261-3db1d30d-6721-4924-baab-e5b453557754.png)
is that normal?

**Comment by cxf2015** [comment]
@riverlijunjie if i reload model after processing every image, the memory usage:
![image](https://user-images.githubusercontent.com/11493837/177751929-781b73b2-e025-4243-9804-ea48250ba871.png)
i think this is normal.

**Comment by cxf2015** [comment]
after processing every image, i call reinit():
![image](https://user-images.githubusercontent.com/11493837/177764977-4a332154-e8a6-4653-8353-9a981763e623.png)

**Comment by riverlijunjie** [comment]
Does the 1.2GB and 4.3GB memory consumption cases run the same models?
It saw there were 2 peaks in the 1.2 GB diagram, what happened at the peak? It is the point of reloading model?
Or could you clarify the details about the 1.2GB diagram?

**Comment by cxf2015** [comment]
@riverlijunjie the 2 peaks in the 1.2 GB diagram is processing two big size image. The other 30 images are of similar size.

**Comment by riverlijunjie** [comment]
@cxf2015 could we close this ticket?

**Comment by cxf2015** [comment]
hi,i tested openvino new version, also have this problem. also need to reload model to fix memory growth problem.Get Outlook for Android

**Comment by riverlijunjie** [comment]
If the number of input shape is dynamic, it is reasonable for memory slow growth due to cache more data for dynamic shape.
If the number of input shape is fixed, the memory should not grow all the time.
Could you give details (models, memory growth, input shape, etc) of your test sample?

**Comment by luvwinnie** [comment]
I'm using the openvino model server 2022.2.0 docker and it have same problem here, when using dynamic shape for OCR model the memory slowly growth.

**Comment by riverlijunjie** [comment]
The memory slowly growth is probably caused by kernel caches, there is a property to limit the cache size during compile_model, you can try set this property like this for python app:


compiled_model = core.compile_model(model=your_model, device_name="CPU", config = {'CPU_RUNTIME_CACHE_CAPACITY':'200'})

**Comment by luvwinnie** [comment]
Does this option able on docker openvino model server? like setting through config.json or something?

**Comment by riverlijunjie** [comment]
I think so, it is a common property which can set with other properties.

**Comment by peterchen-intel** [comment]
@luvwinnie If "memory growth problem" is addressed by setting 'CPU_RUNTIME_CACHE_CAPACITY'?

**Comment by avitial** [comment]
Closing this as it seems issue has been addressed. Feel free to reopen and provide additional information or ask any questions related to this topic.

**Comment by Polaris231** [comment]
hi, i did not find the property(CPU_RUNTIME_CACHE_CAPACITY) in the guide, do you konw how to set this property for C++?

**Comment by vraivon** [comment]
The issue still exists in version 2024.4. If the model always receives input of the same size, there is no problem. However, if the input size keeps changing, memory gradually increases until it runs out.

**Comment by mlukasze** [comment]
`release_memory` method exists for CompiledModel class in CPP API for 24.4 release
it has been added for python API in 24.6 release.

**Comment by vraivon** [comment]
I just noticed a new version while checking for memory leaks and updated to it, but I didn’t catch this small change. Thanks a lot

**Comment by dmitry-gorokhov** [comment]
@vraivon calling release_memory() after each inference might be not the best appraoch from performance perspective. 
Could you please try to set environment variable `ONEDNN_PRIMITIVE_CACHE_CAPACITY=0` in addition to CPU_RUNTIME_CACHE_CAPACITY property? It disables another layer of kernel caching implemented on oneDNN level (which is OV thirdaprty component).

**Comment by vraivon** [comment]
@dmitry-gorokhov 
Thank you, I just noticed that there is still a slight memory leak even with release_memory being used. Let me try again.
