### ISSUE TITLE
[Bug] Unable to load OpenVINO in Electron app node addon

### ISSUE THREAD

**Issue by venki-thiyag** [openvinotoolkit/openvino#13888]
##### System information (version)
- OpenVINO=> 2022.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Problem classification => OpenVINO load issue

##### Detailed description
On Windows, OpenVINO works fine when used from standard Windows application (Win32)
But when used from Electron node addon, on the same machine OpenVINO compile_model API was failing with exception.
Upon further debugging, some path issues were found.

**Comment by mlukasze** [comment]
could you quote this exception message, please?

**Comment by venki-thiyag** [comment]
I have a fix for this issue, looks like when OpenVINO is looking for frontends in some improper path formats. Any idea on how to raise pull requests for this issue?

**Comment by mlukasze** [comment]
The way we could recommend is to create a fork, prepare an fix on a branch, and set a PR to origin master.
At this point GH will call for necessary people on our side to perform a review :)
Please check this link for details --> https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md

**Comment by ilya-lavrenov** [comment]
> I have a fix for this issue, looks like when OpenVINO is looking for frontends in some improper path formats. Any idea on how to raise pull requests for this issue?

frontends are found the folder with openvino.dll

**Comment by venki-thiyag** [comment]
Raised a review with a fix for this problem.

**Comment by venki-thiyag** [comment]
> > I have a fix for this issue, looks like when OpenVINO is looking for frontends in some improper path formats. Any idea on how to raise pull requests for this issue?
> 
> frontends are found the folder with openvino.dll

Yes, right, but when used inside Electron, no frontends are found, changes are raised in pull request solves this problem

**Comment by tomdol** [comment]
Knowing what error you encountered would be very helpful anyway, could you please paste it in the comment?

**Comment by turbobuilt** [comment]
I am encountering this issue with the latest version from npm.  But I can't figure out how to get any errors to show up.  There are no logs, just a crash.  But it works fine on node on windows, just electron doesn't work.

**Comment by venki-thiyag** [comment]
@turbobuilt Faced the same issue in 2022.3 and had to apply the following patch to fix this issue:
[2022.3.0.patch](https://github.com/openvinotoolkit/openvino/files/15392324/2022.3.0.patch)

Did raise review as was held in other issues. Hopefully this helps.

**Comment by mlukasze** [comment]
we can confirm a problem, fix is going to be merge soon
https://github.com/openvinotoolkit/openvino/pull/24558

**Comment by rillomas** [comment]
@mlukasze 
Hi. We are still seeing a crash with OpenVINO 2024.2.0 + Electron 31.0.2 using attached sample. I believe it is the same issue with @turbobuilt  (https://github.com/electron/electron/issues/41913)
Is this supposed to be fixed in 2024.2.0?
[openvino-js-test.zip](https://github.com/user-attachments/files/15951317/openvino-js-test.zip)

```
$ npm start

> openvino-js-test@1.0.0 start
> electron .


Hello World!
[30352:0624/162246.747:ERROR:crashpad_client_win.cc(868)] not connected

$ node main.js
Hello World!
Creating OpenVINO Runtime Core
Created OpenVINO Runtime Core

$ node --version
v22.3.0
```

**Comment by mlukasze** [comment]
with 2024.2 we fixed some problems that blocked integration with electron app
@vishniakov-nikolai will be your support here

**Comment by vishniakov-nikolai** [comment]
> @mlukasze Hi. We are still seeing a crash on Windows 11 23H2 with OpenVINO 2024.2.0 + Electron 31.0.2 using attached sample. I believe it is the same issue with @turbobuilt ([electron/electron#41913](https://github.com/electron/electron/issues/41913)) Is this supposed to be fixed in 2024.2.0? [openvino-js-test.zip](https://github.com/user-attachments/files/15951317/openvino-js-test.zip)
> 
> ```
> $ npm start
> 
> > openvino-js-test@1.0.0 start
> > electron .
> 
> 
> Hello World!
> [30352:0624/162246.747:ERROR:crashpad_client_win.cc(868)] not connected
> 
> $ node main.js
> Hello World!
> Creating OpenVINO Runtime Core
> Created OpenVINO Runtime Core
> 
> $ node --version
> v22.3.0
> ```

Hi @rillomas! Thanks for reporting this issue. Unfortunately, you are right, the problem still exists in Windows version of openvino-node@2024.2 package.

**Comment by rillomas** [comment]
@vishniakov-nikolai Thanks. I'll make a separate issue for this then. Do you know if there is a work around for this in the time being?
