### ISSUE TITLE
[Bug]: apt-get install openvino-2022.3 error: NO_PUBKEY BAC6F0C353D04109

### ISSUE THREAD

**Issue by JinXiaozhao** [openvinotoolkit/openvino#20641]
### OpenVINO Version

2022.3.0

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Issue description

docker images: ubuntu:focal
(1) apt-get install --no-install-recommends -y ca-certificates gnupg wget curl&&     apt-key adv --fetch-keys https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
(2) echo "deb https://apt.repos.intel.com/openvino/2022 focal main" >> /etc/apt/sources.list
(3) apt-get update

error:
Err:6 https://apt.repos.intel.com/openvino/2022 focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com/openvino/2022 focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
E: The repository 'https://apt.repos.intel.com/openvino/2022 focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
 

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by ilya-lavrenov** [comment]
Hi @JinXiaozhao 
Looks like it's a temporary problem with APT repo for 2022 release series. 
Could you please try installation of 2023 releases? They have more features and optimizations

**Comment by evgenytalanin-intel** [comment]
@JinXiaozhao BAC6F0C353D04109 you mentioned is precisely the actual key that is present in actual https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB.

Can you please check that the latest key was really downloaded and processed via apt-key command? I just tried on the empty image and it worked for me.

It's really
```
etalanin@etalanin-mobl:~$ sudo apt update
(skipped)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/openvino/2022 focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
```
initially, but right after
```
etalanin@etalanin-mobl:~$ sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```
(yes, I had this obtained locally via wget to simplify experiments) I received
```
etalanin@etalanin-mobl:~$ sudo apt update
(skipped)
W: https://apt.repos.intel.com/openvino/2022/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
which is pretty explainable deprecation message

**Comment by JinXiaozhao** [comment]
@ilya-lavrenov @evgenytalanin-intel Thanks, the issue has been resolved.

**Comment by jandrioli** [comment]
this is still not fixed on ubuntu 20.04 -- im getting exactly the same message.
