### ISSUE TITLE
RuntimeError: Cannot create ShapeOf layer fc7_mbox_priorbox/0_port id:192

### ISSUE THREAD

**Issue by ananya-p** [openvinotoolkit/openvino#2882]
I am trying to run a face recognition python script which is loading four other models for complete execution.

I am using Raspberry Pi 3B+ (Raspbian Stretch), NCS2 stick with OpenVINO 2020 R3. 

The main script is calling and loading the other models on execution using the NCS2 stick.

I am getting the error:

`RuntimeError: Cannot create ShapeOf layer fc7_mbox_priorbox/0_port id:192`

I am using IE Network and Plugin instead of IE Core. Can that be an issue?

**Comment by jgespino** [comment]
Hi @ananya-p 

Thanks for reaching out, IE Plugin has been deprecated and IE Network will also be deprecated in future software releases. I recommend using IE Core. You mentioned, the python script works well for a couple of models but the error is seen with only this model. Could you share more information about the model?

- Is the model custom trained?
- What framework and topology is the model based on?
- Could you share the model and sample script to reproduce? 

We released OpenVINO toolkit for Raspbian OS version 2021.1 in the last couple of weeks, could you upgrade to the latest release?

https://download.01.org/opencv/2021/openvinotoolkit/2021.1/

Regards,
Jesus

**Comment by ananya-p** [comment]
Hi @jgespino ,

I am in the process of migrating from IE Plugin and IE Network to IE Core already.
I am using the pre-trained models from the OpenVINO toolkit for my program. the models are:

- face-detection-adas-0001

- face-detection-retail-0004

- face-reidentitfication-retail-0095

- head-pose-estimation-adas-0001

- landmarks-regression-retail-0009

My script is just loading the models onto the NCS2 stick and taking the input from the Pi Camera. 

Also, for the OpenVINO toolkit version, I have a compulsion to use OpenVINO toolkit v2020.x, so I'm at a dead-end here.

Thanks!

**Comment by jgespino** [comment]
Hi @ananya-p 

There are some known issues with the OpenVINO toolkit for Raspbian OS, I believe they were fixed on 2020.4, please upgrade to that version and use the same version of models. Let me know if you continue to see the same error.

OpenVINO toolkit for Raspbian OS (2020.4 release):
https://download.01.org/opencv/2020/openvinotoolkit/2020.4/

Models (2020.4):
https://download.01.org/opencv/2020/openvinotoolkit/2020.4/open_model_zoo/models_bin/3/

Regards,
Jesus

**Comment by ananya-p** [comment]
I guess I'll take that up, upgrading OpenVINO toolkit to 2020.4.
I will check that and let you know if any errors persist.

Thanks @jgespino !

**Comment by come-raczy** [comment]
Does this mean that NCS can't be used on raspbian? I am using 2020.3.2 which is the latest version that supports NCS and I have that specific error.
