### ISSUE TITLE
Model Optimizer pip install requirement fail

### ISSUE THREAD

**Issue by dpatel257** [openvinotoolkit/openvino#459]
It built perfect before, maybe because of some package change

`pip3 install -r requirement.txt `

Fails with following error:

```
root@40e857f0fa0d:/home/dldt/model-optimizer# pip3 install --target=/home/build/mo_libs -r requirements.txt
Collecting tensorflow<2.0.0,>=1.2.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7c/fb/7b2c5b3e85ad335b53ca67deb2ef4af574dc0a8759f43b7f45e15005e449/tensorflow-1.14.0-cp35-cp35m-manylinux1_x86_64.whl (109.2MB)
    100% |################################| 109.2MB 13kB/s
Collecting mxnet<=1.5.1,>=1.0.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/98/57/549a1ac1179c9d590cd8fa1c8b4c6bdeb581139f65e3790812c81ae98bbf/mxnet-1.5.1-py2.py3-none-manylinux1_x86_64.whl (23.1MB)
    100% |################################| 23.1MB 69kB/s
Collecting networkx>=1.11 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/41/8f/dd6a8e85946def36e4f2c69c84219af0fa5e832b018c970e92f2ad337e45/networkx-2.4-py3-none-any.whl (1.6MB)
    100% |################################| 1.6MB 698kB/s
Collecting numpy>=1.12.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ff/18/c0b937e2f84095ae230196899e56d1d7d76c8e8424fb235ed7e5bb6d68af/numpy-1.18.2-cp35-cp35m-manylinux1_x86_64.whl (20.0MB)
    100% |################################| 20.0MB 86kB/s
Collecting protobuf==3.6.1 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/bf/d4/db7296a1407cad69f043537ba1e05afab3646451a066ead7a314d8714388/protobuf-3.6.1-cp35-cp35m-manylinux1_x86_64.whl (1.1MB)
    100% |################################| 1.1MB 1.3MB/s
Collecting onnx>=1.1.2 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f7/c9/1ed7a28d784aa867952c7aa5762c8cfa3596dc0f9f7a190725331bb6d3a0/onnx-1.6.0-cp35-cp35m-manylinux1_x86_64.whl (4.8MB)
    100% |################################| 4.8MB 356kB/s
Collecting defusedxml>=0.5.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cf/7a/9744998129fce7e29c5f2d8b0f545913b7383e65d8366fc0ae98d11936af/grpcio-1.28.1.tar.gz (19.5MB)
    100% |################################| 19.5MB 84kB/s
Collecting wheel>=0.26 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Collecting tensorboard<1.15.0,>=1.14.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl (3.1MB)
    100% |################################| 3.2MB 501kB/s
Collecting astor>=0.6.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting wrapt>=1.11.1 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4cf0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz
Collecting absl-py>=0.7.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/1a/53/9243c600e047bd4c3df9e69cfabc1e8004a82cac2e0c484580a78a94ba2a/absl-py-0.9.0.tar.gz (104kB)
    100% |################################| 112kB 5.1MB/s
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488kB)
    100% |################################| 491kB 1.6MB/s
Collecting google-pasta>=0.1.6 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl (57kB)
    100% |################################| 61kB 5.2MB/s
Collecting keras-applications>=1.0.6 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl (50kB)
    100% |################################| 51kB 3.9MB/s
Collecting six>=1.10.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting gast>=0.2.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d6/84/759f5dd23fec8ba71952d97bcc7e2c9d7d63bdc582421f3cd4be845f0c98/gast-0.3.3-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting keras-preprocessing>=1.0.5 (from tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41kB)
    100% |################################| 51kB 5.6MB/s
Collecting graphviz<0.9.0,>=0.8.1 (from mxnet<=1.5.1,>=1.0.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/53/39/4ab213673844e0c004bed8a0781a0721a3f6bb23eb8854ee75c236428892/graphviz-0.8.4-py2.py3-none-any.whl
Collecting requests<3,>=2.20.0 (from mxnet<=1.5.1,>=1.0.0->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 4.9MB/s
Collecting decorator>=4.3.0 (from networkx>=1.11->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting setuptools (from protobuf==3.6.1->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl (582kB)
    100% |################################| 583kB 2.2MB/s
Collecting typing-extensions>=3.6.2.1 (from onnx>=1.1.2->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/0c/0e/3f026d0645d699e7320b59952146d56ad7c374e9cd72cd16e7c74e657a0f/typing_extensions-3.7.4.2-py3-none-any.whl
Collecting futures>=2.2.0; python_version < "3.2" (from grpcio>=1.8.6->tensorflow<2.0.0,>=1.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/47/04/5fc6c74ad114032cd2c544c575bffc17582295e9cd6a851d6026ab4b2c00/futures-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    This backport is meant only for Python 2.
    It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
    For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
    extras_require={':python_version == "2.7"': ['futures']}

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-mi4lb2hk/futures/

```

**Comment by dpatel257** [comment]
Observed on Ubuntu-16.04

**Comment by maxl16** [comment]
Hello @dpatel257 
Seems like it fails to install futures package. Do you see the same output when executing install_prerequisites.sh from <INSTALL_DIR>/deployment_tools/model_optimizer/install_prerequisites ?

If so, you could try the following:
Upgrade pip to latest version
`pip3 install -U pip`
Upgrade futures package manually
`pip3 install -U futures`

**Comment by dpatel257** [comment]
> Do you see the same output when executing install_prerequisites.sh from <INSTALL_DIR>/deployment_tools/model_optimizer/install_prerequisites ?

Yes. I see the same thing happen.

But, this

> If so, you could try the following:
> Upgrade pip to latest version
> `pip3 install -U pip`
> Upgrade futures package manually
> `pip3 install -U futures`

Helped.
I am able to install the requirement fully wit these steps below:
```
pip3 install -U pip
pip3 install -U futures
pip3 install --upgrade setuptools
pip3 install -r requirements.txt
```

I wonder if it will be resolved out of the box in the future.

**Comment by ilya-lavrenov** [comment]
@lazarevevgeny is it resolved in current master?

**Comment by lazarevevgeny** [comment]
@ilya-lavrenov, no it is not resolved. But this issue looks like a package-incompatibility. Do you want to add a requirement for a specific version of "futures" package?
