### ISSUE TITLE
[Bug] Failed to build OpenVINO 2020.3.2 on macOS (11.3.1)

### ISSUE THREAD

**Issue by qiyuangong** [openvinotoolkit/openvino#5605]
Building from source (2020.3.2) failed on macOS (11.3.1)

```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENCV=OFF -DENABLE_MYRIAD=OFF -DENABLE_CLDNN=OFF -DENABLE_GNA=OFF ..
```

Build with clang from Xcode

```
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/inference_engine/convert_function_to_cnn_network.cpp:18:
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:18:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               InterpolateIEAttrs
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:19:18: note: type is not C-compatible due to this default member initializer
    int height = -1;
                 ^~
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:29:3: note: type is given name 'InterpolateIEAttrs' for linkage purposes by this typedef declaration
} InterpolateIEAttrs;
  ^
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:48:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               ResampleIEAttrs
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:49:22: note: type is not C-compatible due to this default member initializer
    bool antialias = true;
                     ^~~~
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:52:3: note: type is given name 'ResampleIEAttrs' for linkage purposes by this typedef declaration
} ResampleIEAttrs;
```

Build with llvm@9 from homebrew

```
In file included from /usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/iosfwd:95:
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:136:77: error: use of undeclared identifier 'wcschr'
wchar_t* __libcpp_wcschr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcschr(__s, __c);}
                                                                            ^
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/thirdparty/pugixml/src/pugixml.cpp:17:
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/thirdparty/pugixml/src/pugixml.hpp:30:
In file included from /usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/exception:80:
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
      ~~^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/cstddef:50:9: error: no member named 'size_t' in the global namespace
using ::size_t;
      ~~^
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/inference_engine/blob_transform.cpp:5:
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/plugin_api/blob_transform.hpp:13:
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/include/ie_blob.h:12:
In file included from /usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/cstring:60:
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
```

**Comment by ilyachur** [comment]
@qiyuangong Could you try to use the latest OpenVINO version?

**Comment by qiyuangong** [comment]
> @qiyuangong Could you try to use the latest OpenVINO version?

Build with master branch (https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS). The Same Errors

Build with Xcode Clang

```
[  4%] [cpplint] /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/src/ngraph_ops/eltwise.cpp
In file included from /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/legacy_api/src/convert_function_to_cnn_network.cpp:20:
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:18:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               InterpolateIEAttrs
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:19:18: note: type is not C-compatible due to this default member initializer
    int height = -1;
                 ^~
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:29:3: note: type is given name 'InterpolateIEAttrs' for linkage purposes by this typedef declaration
} InterpolateIEAttrs;
  ^
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:48:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               ResampleIEAttrs
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:49:22: note: type is not C-compatible due to this default member initializer
    bool antialias = true;
                     ^~~~
/Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/include/ngraph_ops/interp.hpp:52:3: note: type is given name 'ResampleIEAttrs' for linkage purposes by this typedef declaration
} ResampleIEAttrs;
  ^
[  4%] [cpplint] /Users/qiyuangong/Develop/Gitremote/openvino/inference-engine/src/transformations/src/ngraph_ops/fully_connected.cpp
```

Build with llvm@9 from homebrew

```
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:136:77: error: use of undeclared identifier 'wcschr'
wchar_t* __libcpp_wcschr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcschr(__s, __c);}
                                                                            ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:143:87: error: use of undeclared identifier 'wcspbrk'
wchar_t* __libcpp_wcspbrk(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcspbrk(__s1, __s2);}
                                                                                      ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:150:78: error: use of undeclared identifier 'wcsrchr'; did you mean 'wcschr'?
wchar_t* __libcpp_wcsrchr(const wchar_t* __s, wchar_t __c) {return (wchar_t*)wcsrchr(__s, __c);}
                                                                             ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:138:16: note: 'wcschr' declared here
const wchar_t* wcschr(const wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:157:86: error: use of undeclared identifier 'wcsstr'; did you mean 'wcschr'?
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                     ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:140:16: note: 'wcschr' declared here
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:157:86: error: no matching function for call to 'wcschr'
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                     ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:140:16: note: candidate disabled: <no message provided>
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
               ^
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:157:93: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'const wchar_t *'
wchar_t* __libcpp_wcsstr(const wchar_t* __s1, const wchar_t* __s2) {return (wchar_t*)wcsstr(__s1, __s2);}
                                                                                            ^~~~
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/wchar.h:140:38: note: passing argument to parameter '__s' here
      wchar_t* wcschr(      wchar_t* __s, wchar_t __c) {return __libcpp_wcschr(__s, __c);}
```

**Comment by ilyachur** [comment]
@qiyuangong did you use the latest master? 
Could you double check?
Because I see that in the master branch the `interp.hpp` file was moved and issues were fixed: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/legacy_api/include/legacy/ngraph_ops/interp.hpp#L18

**Comment by qiyuangong** [comment]
> @qiyuangong did you use the latest master?
> Could you double check?
> Because I see that in the master branch the `interp.hpp` file was moved and issues were fixed: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/legacy_api/include/legacy/ngraph_ops/interp.hpp#L18

Hi @ilyachur 

After re-clone latest master branch, I have successfully built from source with 
```
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j 8
```

However, build with OpenMP threading still cannot pass.

**Comment by ilyachur** [comment]
@qiyuangong What issue did you get?
```
clang: error: unsupported option '-fopenmp'
```
Or something else?

**Comment by qiyuangong** [comment]
> @qiyuangong What issue did you get?
> 
> ```
> clang: error: unsupported option '-fopenmp'
> ```
> 
> Or something else?

If using clang from Xcode, will encounter 

```
clang: error: unsupported option '-fopenmp'
```

If using llvm@9, will encounter

```
/usr/local/Cellar/llvm@9/9.0.1_2/bin/../include/c++/v1/string.h:73:64: error: use of undeclared identifier 'strchr'
char* __libcpp_strchr(const char* __s, int __c) {return (char*)strchr(__s, __c);}
```

**Comment by ilyachur** [comment]
We highly recommend to use TBB for parallelism, can you use it?

**Comment by qiyuangong** [comment]
> We highly recommend to use TBB for parallelism, can you use it?

Will try TBB version. Thanks :)
Issue closed
